### PR TITLE
hasanger said to fix code + people wanted fences to affect gameplay

### PR DESCRIPTION
**Pull request by emeraldn30**
https://discord.com/channels/1077043833621184563/1228479518692343808

### CODE REVIEW

**Comment by 1092384** [comment]
You didn't even rename the obstacle assets

**Comment by emeraldn30** [comment]
check pull 298

**Comment by emeraldn30** [comment]
I think it should work if you pull both

**Comment by 1092384** [comment]
stop farming commits

**Comment by emeraldn30** [comment]
why does it matter

**Comment by emeraldn30** [comment]
just pull both

**Comment by itsNMD404** [comment]
Im gonna let hasanger deal with this pr lmfao

**Comment by itsNMD404** [comment]
Def not shifting responsibility

**Comment by emeraldn30** [comment]
also changed the port_shed to shed

**Comment by 1092384** [comment]
You missed something

**Comment by emeraldn30** [comment]
what did I miss

**Comment by 1092384** [comment]
go playtest it

**Comment by emeraldn30** [comment]
if you are so sure I missed something than why don't you fix it

**Comment by 1092384** [comment]
I don't feel like it

**Comment by emeraldn30** [comment]
so there isn't any issue urgent enough to be fixed

**Comment by emeraldn30** [comment]
got it

**Comment by itsNMD404** [comment]
Please stop spamming this place with comments, im getting spammed emails

**Comment by kenos1** [comment]
Unsubscribe button:

**Comment by itsNMD404** [comment]
kenos

**Comment by itsNMD404** [comment]
As this is just a simple renaming, we will not be adding this.

**Pull request closed without merging**
