### PR TITLE
update readme for newbie

### PR DESCRIPTION
**Pull request by synasapmob**
first time I'm clone this project and trying run but doesn't work, 
I had spent fewer hours to fix them, and anyway if you have documentation clarify that'll useful and quickly for you

### CODE REVIEW

**Comment by pap-24** [comment]
is this a joke

**Comment by synasapmob** [comment]
sorry my misstake, let's me try again

**Comment by ersek-huba** [comment]
> is this a joke (wtf is surviv fun)



Very interesting (ngl, at first I thought it will be another resurviv clone)

**Comment by synasapmob** [comment]
> > is this a joke (wtf is surviv fun)
> 
> 
> 
> Very interesting (ngl, at first I thought it will be another resurviv clone)

hey guy, i just trying to contribution this project, and I'm missing copy/paste that's reason another domain surviv here.

stopped behaviour please.

**Comment by synasapmob** [comment]
this PR move to https://github.com/HasangerGames/suroi/pull/443

**Pull request closed without merging**
