### PR TITLE
rocosinex loot table change

### PR DESCRIPTION
**Pull request by emeraldn30**
"It's extremely annoying when someone who knows how to quickswitch has double tangos, because they basically rack kills. We have a cz600 sniper and a tango sniper, that's enough in an average round"

### CODE REVIEW

**Comment by 1092384** [comment]
stop making random prs

**Comment by emeraldn30** [comment]
Amy told me to stop pinging her

**Comment by emeraldn30** [comment]
I've only pinged her 1,232 times

**Comment by emeraldn30** [comment]
I think she's overreacting

**Comment by itsNMD404** [comment]
Bro is FARMING his github comments. Closed due to poor implementation and lack of justification for said changes.

**Pull request closed without merging**
