### PR TITLE
Darker/dimmed backdrop on teams menu

### PR DESCRIPTION
**Pull request by pap-24**
Disables the splash ui's interaction and makes it darker by using the brightness filter when the teams menu is open
photo

### CODE REVIEW

**Comment by bien-star** [comment]
Would it be possible to make it fade in

**Comment by pap-24** [comment]
I will look into it tommorow

**Comment by bien-star** [comment]
I meant that the background could slowly dim when selecting the team menu rather than immediatley going dark

**Comment by pap-24** [comment]
I don't think so, because the splash ui's fade is controlled by the play buttons etc

**Pull request merged**
