### PR TITLE
 I Add Better Mode System, "Server" Side, and the mode can chang…

### PR DESCRIPTION
**Pull request by kaklikOf13**
feat: I Add a map extends system
feat: I Add Game Server Side Mode Configuration

https://github.com/HasangerGames/suroi/assets/101949387/024f1832-83eb-45ec-8fc9-47efb9f2a074

I add Map Extends
image
image

### CODE REVIEW

**Comment by kaklikOf13** [comment]
Would this be useful for you?

**Comment by kaklikOf13** [comment]
note: When I was running, I needed to take off the watch, because it kept resetting the server without alterations

**Comment by bien-star** [comment]
nice

**Review by kaklikOf13 — COMMENTED** [review]
I accidentally added the package.json change to the commit.
but is working, without hard bugs

**Pull request closed without merging**
