### PR TITLE
increase readability

### PR DESCRIPTION
**Pull request by Domincog**
## Description

I added code comments to just one page (vector.ts). Probably over commented, but better than bare code. 

## Type of change

Please delete options that are not relevant.

* **docs**: Documentation only changes.
* **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc).
* **refactor**: A code change that neither fixes a bug nor adds a feature.

### CODE REVIEW

**Comment by Domincog** [comment]
For context, I'm struggling to understand your codebase and feel it direly needs developer documentation. My idea is to systematically start from the base files (not importing from other files) and work up from there so I (and others) can understand the codebase better. I've only developed in Java/Python/C# and have almost zero experience with typescript or even JavaScript for that matter.

I started with only one file because of time constraints and because I'm not sure if this is okay with you or not.

**Comment by ei-pi** [comment]
The intention is good, but I would like to request the use of [JSDoc comments](https://jsdoc.app) as opposed to plain comments, because they are supported by code editors (hovering your mouse over a symbol which has a documentation comment attached will show the appropriate comment) and tend to be easier to read, since information is organized into a clear and precise format.

**Comment by Domincog** [comment]
I updated the comments, thanks for the suggestion.

**Comment by leo78913** [comment]
Thanks!

**Pull request merged**
