### PR TITLE
Added Troll

### PR DESCRIPTION
**Pull request by EagleEye2010**
Added cool troll in tango crate

there is a slight chance that a Tango 51 will be replaced with a G19

### CODE REVIEW

**Comment by hsanger** [comment]
This is a fun idea, but I think the `weight` should be more like 1

**Comment by EagleEye2010** [comment]
Also just buffed Stoner 63 because I think that it was too weak for its rarity.

**Comment by kenos1** [comment]
nerf g19 it's too good for it's rarity

**Comment by EagleEye2010** [comment]
fr fr

**Comment by EagleEye2010** [comment]
Stoner 63 does about the same DPS as the AUG, yet is the rarest weapon in the game, with the exception of Tango 51 (and now Tango always spawns on the ship). If this gun does the same DPS as the AUG, yet creates such crazy recoil and terrible accuracy, the AUG is honestly better. The Stoner 63 should be buffed.

**Comment by kenos1** [comment]
yes but you don't need to reload often

**Comment by CroissantEdit** [comment]
stoner is op, scopes are a lot more common in this game, and you can just frike people over, stoner also have a 2x obstacle damage, more bullet max distance and bullet damage. On paper it looks underpowered, but in real game is busted

**Comment by hsanger** [comment]
bleh

**Comment by kenos1** [comment]
bleh

**Pull request closed without merging**
