### PR TITLE
feat: added game settings tab under settings; added scope looping tog…

### PR DESCRIPTION
**Pull request by ScaredPenguinXXL**
# Suroi PR Submission Template

## Description

Added a game settings tab under settings and added a scope looping toggle.

## Type of change

* **feat**: A new feature.

## How Has This Been Tested?

Tested by running locally run dev server.

### CODE REVIEW

**Review by 1092384 — COMMENTED** [review]
Can you send video?

**Comment by ScaredPenguinXXL** [comment]
> Can you send video?

https://github.com/HasangerGames/suroi/assets/89851117/7b357f5c-493d-4a62-93de-03aad9777345

**Review by leia-uwu — CHANGES_REQUESTED** [review]
imo the volume tab should still be the first tab

**Comment by hsanger** [comment]
I think the option should be in the Interface tab

**Comment by 1092384** [comment]
Once there are more settings I think we could make a seperate "game settings" tab

But for now yeah put it in interface

**Review by 1092384 — APPROVED** [review]

**Pull request merged**
