### PR TITLE
Golden HP-18

### PR DESCRIPTION
**Pull request by Crimson-Haze**
here are the models
Untitled (2)
Untitled (6)
Untitled (7)

the golden hp-18 would have a 1% chance of replacing the normal hp-18, it would be more powerful because of its rarity.
if you would like to me to alter the stats a little i can do that.
positives
2 extra damage
2 extra pellets per shot
1 extra bullet (6 instead of 5)
reload time is 0.25 seconds
recoil strength is 0.4
and recoil time is 0.400
negatives
higher spread (20 instead of 18)
move spread increased (24 instead of 20)

### CODE REVIEW

**Comment by 1092384** [comment]
womp womp

**Comment by Crimson-Haze** [comment]
> womp womp

why are saying "womp womp"?

**Comment by kenos1** [comment]
Just get the vepr

**Comment by Crimson-Haze** [comment]
I closed this because everything broke I will fix it and open a new one

**Pull request closed without merging**
