### PR TITLE
Feat: disable kill leader sounds option

### PR DESCRIPTION
**Pull request by ChpssCode**
Tested by turning on kill leader sounds, and sounds were played. Turned off the option and sounds were not played.

### CODE REVIEW

**Comment by leia-uwu** [comment]
conflicting with master

**Comment by ChpssCode** [comment]
Bro really said “conflicting with master” when it could have been merged two days ago and there never would have been conflict

smh

**Comment by leia-uwu** [comment]
L

**Comment by 1092384** [comment]
Arguing

**Comment by kenos1** [comment]
:skull:

**Pull request closed without merging**
