### PR TITLE
Balance

### PR DESCRIPTION
**Pull request by kaklikOf13**
Changes To Be Committed:
	modified:   common/src/definitions/guns.ts
Guns Changes To Be Committed:
	M3K:
		-1 Capacity
		-15% Range
	HP18:
		-5% Shot Spread
		+10% Range
	Flues:
		+5% Range

### CODE REVIEW

**Comment by DamienVesper** [comment]
no

**Comment by DamienVesper** [comment]
Reasons being this messes up the categorical "class" system that the guns form. Already went into a lot of balancing regarding shotguns vs. snipers. Definitely not messing it up on the fly immediately.

**Comment by DamienVesper** [comment]
oops i closed it

**Comment by 1092384** [comment]
> oops i closed it

Good

**Pull request closed without merging**
