### PR TITLE
buff barrett pls

### PR DESCRIPTION
**Pull request by HughJassss**
**pls** listen to this

> **_### im serious_**

its **balls**
for its **rarity** and **special ammo**, it **lowkey suckß**
its also 12.7 so it should deal more damage to obstacles

**chart**
Level 3 armor shots to kill
mosin-tango-barret
5 shots-4shots-3shots

For one extra shot, the tango kills but it has more common ammo, less spread, and shorter reload. Less recoil and fire delay make it easier to play with too.
Make the Barret a 2 shot kill at level 3 and give it more obstacle damage to make it a good contender in the sniper rifle competition

### CODE REVIEW

**Comment by HughJassss** [comment]
or just delete it cuz tango superior

**Comment by zedaes** [comment]
no one's gonna delete the tango lol

**Comment by HughJassss** [comment]
I never said delete tango 💀

**Comment by ersek-huba** [comment]
No more Barrett, no more problem.

**Comment by DamienVesper** [comment]
Closing as invalid.

**Pull request closed without merging**
