### PR TITLE
Update maps.ts, more cover without 200 river rocks

### PR DESCRIPTION
**Pull request by emeraldn30**

### CODE REVIEW

**Comment by Leon-9982** [comment]
Wtf is 15 extra river rocks going to do? It's a barely noticeable change, I added the 200 rocks to mine because rivers just make you insanely vulnerable when your in it.

**Comment by bien-star** [comment]
> rivers just make you insanely vulnerable when your in it.

Yes, that's the point. Rivers are supposed to be an obstacle that impedes you.

**Comment by 1092384** [comment]
Close this

**Comment by kaklikOf13** [comment]
XD

**Comment by DamienVesper** [comment]
Not going to be implemented.

**Pull request closed without merging**
