### PR TITLE
Chpserz croissant dev

### PR DESCRIPTION
**Pull request by ChpssCode**
- Added River Rocks
- Added Seax

### CODE REVIEW

**Comment by CroissantEdit** [comment]
I added riverrocks a long time ago but i when i accidently commited some bad code to that branch,  it went inside the pull request lmfao

**Comment by ChpssCode** [comment]
Ye

**Comment by CroissantEdit** [comment]
@ChpssCode sea pickle/ sea grass when :trollface:

**Comment by pythoncat1** [comment]
sex axe

**Comment by SovietNuclearFridgeBomb** [comment]
yippee :3333

**Comment by Compositr** [comment]
blehhhh

**Comment by pythoncat1** [comment]
image
:(

**Pull request closed without merging**
