### PR TITLE
Usas should come in the lux crate sometimes

### PR DESCRIPTION
**Pull request by Hashimk2**
If this code is wrong, plz fix it

### CODE REVIEW

**Comment by 1092384** [comment]
No, because there are already several ways to reliably get the weapon

**Comment by Hashimk2** [comment]
> No, because there are already several ways to reliably get the weapon

That is in the harvest event

**Comment by Hashimk2** [comment]
> No, because there are already several ways to reliably get the weapon

What are the several ways to reliably get the weapon in the normal mode?

**Comment by 1092384** [comment]
We are not adding the usas-12 to normal mode

**Comment by Hashimk2** [comment]
> We are not adding the usas-12 to normal mode

Why not?

**Comment by 1092384** [comment]
Because it's too overpowered for normal mode

Also you fucked up your code and now it always drops both a CZ and USAS-12

**Comment by SurvivWasTheBestGame** [comment]
> Because it's too overpowered for normal mode
> 
> Also you fucked up your code and now it always drops both a CZ and USAS-12

That is cool

**Comment by Hashimk2** [comment]
> Because it's too overpowered for normal mode
> 
> Also you fucked up your code and now it always drops both a CZ and USAS-12

In the harvest event? 
Or in the normal?

**Comment by Emeraldm5** [comment]
> Because it's too overpowered for normal mode
> 
> Also you fucked up your code and now it always drops both a CZ and USAS-12

Why do you swear?

**Comment by Emeraldm5** [comment]
> We are not adding the usas-12 to normal mode

Why not add the similar gun to the usas. I think it is called something with M50…

**Comment by 1xvc** [comment]
ty katloo for closing this

**Pull request closed without merging**
