### PR TITLE
Refactor: Updated mcx_spear_world.svg

### PR DESCRIPTION
**Pull request by 1092384**
Simplified world loot image

# Suroi PR Submission Template

## Description

Re-uploaded simpler version of MCX-spear world image.

## Type of change

Please delete options that are not relevant.

* **refactor**: A code change that neither fixes a bug nor adds a feature.

## How Has This Been Tested?

https://github.com/HasangerGames/suroi/assets/66282302/35a2ecf7-0140-46e4-b6e4-b97cc4859974

Tested locally using downloaded repo.

### CODE REVIEW

**Comment by leo78913** [comment]
looks a bit better but the outline colors are not consistent with the other guns
the outline / stroke should be the fill color with 9% brightness using an HSL color picker

**Review by leo78913 — CHANGES_REQUESTED** [review]
see the comment

**Comment by 1092384** [comment]
> looks a bit better but the outline colors are not consistent with the other guns the outline / stroke should be the fill color with 9% brightness using an HSL color picker

Ok I'll fix it

**Comment by 1092384** [comment]
Wait would I put it in a new commit?

**Comment by 1092384** [comment]
Can someone close this

**Pull request closed without merging**
