### PR TITLE
Added AK-74 U

### PR DESCRIPTION
**Pull request by EagleEye2010**
Added AK 74-U

- Used AK-47 images to create a similar look between the AK-47.
- Added a folded skeleton stock (visible in world image).
- Increased accuracy, damage, and reload times thanks to the 5.45mm bullet. (I'll add that ammo type later)
- About the same spawn rate as MCX Spear.
- No special audio.

### CODE REVIEW

**Comment by emeraldn30** [comment]
wait what lmao

**Comment by emeraldn30** [comment]
you know 545 isn't in normal

**Comment by emeraldn30** [comment]
also your loot image has the stock folded in while the world image has it deployed unlike other folding stocks (mp40 & vityaz)

**Comment by EagleEye2010** [comment]
Ok fixed.

**Comment by pythoncat1** [comment]
Why is the foregrip’s topdown so goofy

**Comment by itsNMD404** [comment]
Wont add for now.

**Pull request closed without merging**
