### PR TITLE
Update buildings.ts

### PR DESCRIPTION
**Pull request by Leon-9982**
Removed original center lootspawner and added two to the entrances. 
Removed all small boxes as they cramped the space too much. 
Readjusted location of ammo crate and applied a 0.97 scale over it to make some space around them.
Added a regular crate to the center.
Remade PR because I forgot to add the center regular crate.
image

P.S Check code for errors.

### CODE REVIEW

**Comment by 1092384** [comment]
you know you can just push more commits to the same pr

**Comment by Leon-9982** [comment]
mb didnt know

**Comment by bien-star** [comment]
Did you also move and scale the hitboxes of the ammo crates?

**Comment by bien-star** [comment]
Also why did you remove the boxes

**Comment by Leon-9982** [comment]
It looks too messy with them there, I've added two loot spawners to compensate for them

**Comment by Leon-9982** [comment]
> Did you also move and scale the hitboxes of the ammo crates?

When I add the sclae property, it adjusts the size and hitboxes of the object, so yes.

**Comment by Leon-9982** [comment]
> The boxes that are in the warehouse use the box loot table, whereas you added another warehouse tier spawner which is completely different. Also, there is now a middle box which wasn’t there before. Overall, there’s a lot better loot available now. What’s the reasoning for this change?

Added the center box because I wanted to basically, cuz it felt empty without it, and I didn't know what other tables existed so just used the existing one. @hsanger can edit the spawner loot table if he wishes so.

**Comment by Leon-9982** [comment]
I don't mind removing the loot spawners.

**Comment by emeraldn30** [comment]
also there shouldn't be a 0.97 size multiplier on the ammo crates if you can help it imo

**Comment by Compositr** [comment]
Yeah be careful with scaling down stuff cause it messes up the breaking scaling

**Comment by kaklikOf13** [comment]
I Like

**Review by Compositr — CHANGES_REQUESTED** [review]
L#371-372 Scaling down is not optimal as it messes with the breaking animation.

**Comment by Leon-9982** [comment]
> L#371-372 Scaling down is not optimal as it messes with the breaking animation.

I've removed scaling, and did some other stuff in my newest commit @Compositr

**Review by Compositr — APPROVED** [review]
Looks good to me

**Comment by bien-star** [comment]
If we're going to go with this maybe it could be one of two possible layouts? Randomly either this one or the original. 
Also hopefully once there's some more buildings on the map we can switch to fewer and larger warehouses rather than these dollar store ones.

**Comment by 1092384** [comment]
lmfao

**Pull request closed without merging**
