### PR TITLE
Delete client/src/leaderboard.ts

### PR DESCRIPTION
**Pull request by 1092384**
Useless empty file

### CODE REVIEW

**Comment by leia-uwu** [comment]
no need to remove it, it will be used soon™️ and its actually referenced in some places

**Comment by DamienVesper** [comment]
pro tip: if CI fails you probably goofed

**Comment by 1092384** [comment]
:trollface:

**Comment by 1092384** [comment]
Honestly I should have looked to see if deleting this would affect anything

Sorry but I make dumb mistakes like this all the time

**Pull request closed without merging**
