### PR TITLE
Update melees.ts (baseball bat can pierce)

### PR DESCRIPTION
**Pull request by bien-star**
In surviv.io the wood axe could break ammo crates along with some other melee weapons, the only way to break the ammo crates in suroi is with the maul. I think the baseball bat should be buffed to be able to break crates, so that they have some more unility  (at least as a placeholder until we have more piercing meeles)

### CODE REVIEW

**Comment by emeraldn30** [comment]
baseball bat is blunt

**Comment by emeraldn30** [comment]
how could it pierce

**Comment by emeraldn30** [comment]
axe and maul have large blades or are made of metal

**Comment by bien-star** [comment]
> how could it pierce

for gameplay purpouses as a placeholder

**Pull request closed without merging**
