### PR TITLE
Controller joysticks

### PR DESCRIPTION
**Pull request by Arman-AIi**
https://github.com/user-attachments/assets/b26be052-46c6-4f7f-ae2b-729a27888fd7

### CODE REVIEW

**Comment by Arman-AIi** [comment]
@ei-pi

**Comment by ei-pi** [comment]
1) lint please
2) should be rebased onto master instead of having a random merge in the middle
3) see if you can make it not run on rAF (requestAnimationFrame) and have it be event-based instead—running stuff on `rAF` unnecessarily is just meh

**Comment by kenos1** [comment]
> 1. lint please
> 2. should be rebased onto master instead of having a random merge in the middle
> 3. see if you can make it not run on rAF (requestAnimationFrame) and have it be event-based instead—running stuff on `rAF` unnecessarily is just meh

Event-based I'm pretty sure is impossible with the web controller API, but that still means you should use better alternatives.

**Comment by Arman-AIi** [comment]
@ei-pi 
1. Done
2. Done, will also do this in the future
3. It is unfortunately not possible to have gamepad API to be event-based, but I did implement Pixi.js ticker as kenos said

**Pull request closed without merging**
