### PR TITLE
feat: :sparkles: Poisson Disc spawn mode

### PR DESCRIPTION
**Pull request by kenos1**
This spawn mode is like random but with a minimum distance between players

### CODE REVIEW

**Comment by kenos1** [comment]
BRUH WHY DID THE DUAL WIELD STUFF PUSH

**Comment by blazingyoda** [comment]
CROISSANTS 4TH ATTEMPT, WILL HE SUCCEED AT NOT GETTING AN ERROR THIS TIME?!!?!??!?!
no

**Comment by leia-uwu** [comment]
me when unrelated formatting changes
pls disable your auto formatter smh

**Comment by kenos1** [comment]
pov pnpm lint

**Pull request merged**
