### PR TITLE
Win die emotes (need someone do to the ui part)

### PR DESCRIPTION
**Pull request by BeanieMen**

### CODE REVIEW

**Comment by me505** [comment]
idk what happened to pnpm lock

**Comment by pythoncat1** [comment]
@BeanieMen ill do ui, ill make pr to your git when done

**Comment by pythoncat1** [comment]
@BeanieMen it seems that your implementation server side is incomplete, as death emotes disappear instantly after player death.

**Comment by BeanieMen** [comment]
I have lost all my time

**Comment by BeanieMen** [comment]
I am now fucked because of finals

**Pull request closed without merging**
