### PR TITLE
Pixi refactor dev

### PR DESCRIPTION
**Pull request by CoreyPlays**
# Suroi PR Submission Template

## Description

Please include a summary of the change and which issue is fixed. Please also include relevant motivation and context. List any dependencies that are required for this change.

## Type of change

Please delete options that are not relevant.

* **feat**: A new feature.
* **fix**: A bug fix.
* **docs**: Documentation only changes.
* **style**: Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc).
* **refactor**: A code change that neither fixes a bug nor adds a feature.
* **perf**: A code change that improves performance.
* **test**: Adding missing tests.
* **chore**: Changes to the build process or auxiliary tools and libraries such as documentation generation.
* **deploy**: An automated commit, normally from a workflow.

## How Has This Been Tested?

Please describe the tests that you ran to verify your changes. Please also list any relevant details for your test configuration.

### CODE REVIEW

**Comment by leia-uwu** [comment]
there's already a PR open to merge this branch
#104

**Comment by kenos1** [comment]
bruh

**Comment by 1092384** [comment]
Is this guy trying to release the update early

**Comment by kenos1** [comment]
clearly

**Pull request closed without merging**
