### PR TITLE
Fix sound latency, max mouse distance and change certain sound volumes

### PR DESCRIPTION
**Pull request by IOMAN12**

### CODE REVIEW

**Review by 1092384 — APPROVED** [review]

**Comment by ChpssCode** [comment]
Bro 22 commits for 8 lines of code 💀

**Comment by kenos1** [comment]
pov: github text editor

**Comment by kenos1** [comment]
also how does this decrease latency

**Comment by DamienVesper** [comment]
closing as stale, reopen as needed

**Pull request closed without merging**
