### PR TITLE
created a heal particle

### PR DESCRIPTION
**Pull request by Lightningeek**
# Suroi PR Submission Template

## Description

Code in a heal particle I added an

## Type of change

added an image

## How Has This Been Tested?

Look I can't test this im not smart enough to do the shenanigans to run this and test, its just an image I wanted to add to say that I contributed, its not gonna be active, its just an image you guys could use

### CODE REVIEW

**Comment by leo78913** [comment]
this is using an embedded png inside the svg :/
which is why the client building is failing when generating the texture atlas i think

**Comment by Lightningeek** [comment]
> this is using an embedded png inside the svg :/ which is why the client building is failing when generating the texture atlas i think

hmm alr then ill try making an svg instead

**Comment by Lightningeek** [comment]
so I made another svg file that doesn't embed png with base 64, and if this doesn't work im also attaching the original png
heal_particle
heal_particle

**Comment by leo78913** [comment]
yeah its an svg now, can you update the commit?

**Comment by Lightningeek** [comment]
Commit updated

**Comment by leo78913** [comment]
thanks!

**Pull request merged**
